"""Generate common-character webfonts; retain the originals as full fallbacks."""

from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
FONTS = ROOT / "public/assets/fonts"
UNICODE_RANGE = "U+0-FF,U+131,U+152-153,U+300-36F,U+2000-206F,U+20A0-20CF,U+2100-214F,U+2190-21FF"
CODEPOINTS = subset.parse_unicodes(UNICODE_RANGE)
SPECS = [
    (
        "source-sans-pro",
        f"SourceSansPro-{style}",
        f"VeritasSans-{style}",
        "Veritas Sans",
        weight,
        "normal",
    )
    for style, weight in [("Regular", "400"), ("SemiBold", "600"), ("Bold", "700")]
] + [
    (
        "monaspace-neon",
        "MonaspaceNeonVar",
        "VeritasMono",
        "Veritas Mono",
        "200 800",
        "oblique 0deg 11deg",
    )
]


def css_range(codepoints):
    ranges = []
    for point in sorted(codepoints):
        if ranges and point == ranges[-1][1] + 1:
            ranges[-1][1] = point
        else:
            ranges.append([point, point])
    return ",".join(
        f"U+{start:X}" if start == end else f"U+{start:X}-{end:X}" for start, end in ranges
    )


def generate():
    css = ["/* Generated by scripts/subset-fonts.py. Full faces precede preferred subsets. */"]
    for directory, original, output, family, weight, style in SPECS:
        source = FONTS / directory / f"{original}.woff2"
        target = source.with_name(f"{output}-latin.woff2")
        font = TTFont(source, recalcTimestamp=False)
        full_range = css_range(font.getBestCmap())
        options = subset.Options()
        options.layout_features = ["*"]
        options.name_IDs = ["*"]
        options.name_languages = ["*"]
        options.name_legacy = True
        options.notdef_glyph = True
        options.notdef_outline = True
        subsetter = subset.Subsetter(options=options)
        subsetter.populate(unicodes=CODEPOINTS)
        subsetter.subset(font)
        # Respect reserved font names while preserving copyright/license records.
        for record in font["name"].names:
            if record.nameID in (0, 7, 8, 9, 10, 11, 12, 13, 14):
                continue
            value = record.toUnicode()
            for old, new in [
                ("Source Sans Pro", "Veritas Sans"),
                ("SourceSansPro", "VeritasSans"),
                ("Monaspace Neon Var", "Veritas Mono"),
                ("MonaspaceNeonVar", "VeritasMono"),
            ]:
                value = value.replace(old, new)
            record.string = value.encode(record.getEncoding())
        font.save(target)
        common_range = css_range(font.getBestCmap())
        font.close()
        print(f"{source.name}: {source.stat().st_size:,} -> {target.stat().st_size:,} bytes")
        for filename, unicode_range in [(source.name, full_range), (target.name, common_range)]:
            css.extend(
                [
                    "@font-face {",
                    f"    font-family: '{family}';",
                    f"    src: url('/assets/fonts/{directory}/{filename}') format('woff2');",
                    f"    font-weight: {weight};",
                    f"    font-style: {style};",
                    "    font-display: swap;",
                    f"    unicode-range: {unicode_range};",
                    "}",
                ]
            )
    (ROOT / "src/styles/fonts.css").write_text("\n".join(css) + "\n", encoding="utf-8")


if __name__ == "__main__":
    generate()
